Searchapi
EBM-2017-2018/OKLM pull request #21
Opened 2018-03-13 09:32 UTC by Hazegard

2018-03-13 10:25 UTC, Willtock commented on backend/src/api/resources/users/user.controller.js
> +            message: 'L\'utilisateur n\' pas pu être trouvé',
faute de frappe, il manque un "a"

2018-03-13 10:37 UTC, Ekarz commented
Ne pas accepter la PR, Maxime croit avoir perdu des trucs de son ancien pc

2018-03-13 16:32 UTC, Hazegard commented
C'est bon, je les ai retrouvé :)

2018-03-14 07:05 UTC, Hazegard commented
CC @EBM-2017-2018/oklm

2018-03-14 09:35 UTC, clementm requested changes

2018-03-14 09:35 UTC, clementm commented on backend/src/api/resources/documents/documents.controller.js
> +const addAuthorsToListDocuments = async documents => {
Pourquoi eslint-disable ici ?

2018-03-14 09:35 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +  return Promise.all(documents.map(doc => addAuthorToDocument(doc)));
plutôt récupérer les IDs des documents, et construire la requête MongoDB ensuite : ça permet d'éviter de rechercher plusieurs fois le même auteur, et de ne faire (potentiellement ?) qu'une seule requête ?

2018-03-14 14:31 UTC, Hazegard commented
Change done @EBM-2017-2018/oklm

2018-03-14 14:44 UTC, clementm requested changes

2018-03-14 14:44 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +  console.log(authorsId);
console.log

2018-03-14 14:44 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +const addAuthorToDocument = async (document, author) => {
cette fonction ne devrait pas être async

2018-03-14 14:44 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +  return Promise.all(documents.map(doc => addAuthorToDocument(doc, authorsDict[doc.author])));
pas besoin de Promise.all ici, cf commentaire au-dessus

2018-03-14 16:27 UTC, clementm approved these changes

2018-03-14 16:27 UTC, m1ch3lcl commented on backend/src/api/search/index.js
> + *    contents=categories,documents
à modifier @Hazegard

2018-03-14 16:38 UTC, merged