Upload
EBM-2017-2018/OKLM pull request #22
Opened 2018-03-13 09:48 UTC by Ekarz

2018-03-13 13:04 UTC, m1ch3lcl commented
il faut merge la PR #23 avant d'accepter celle-ci :slightly_smiling_face:

2018-03-13 22:42 UTC, nymous requested changes

2018-03-13 22:42 UTC, nymous commented on backend/src/api/resources/documents/document.model.js
> +  fileName: {
`fileName` ou `originalFileName` ? Je ne sais plus ce qu'on avait décidé

2018-03-13 22:42 UTC, nymous commented on backend/src/api/resources/documents/documents.controller.js
> +    // eslint-disable-next-line
Pourquoi désactiver eslint ici ?

2018-03-13 22:42 UTC, nymous commented on backend/src/api/resources/documents/documents.controller.js
> +    doc.uri = url.resolve('/api/download/', doc._id.toString());
Pour faire vraiment propre, il faudrait ne pas stocker l'URL en base si jamais c'est un fichier uploadé, et la calculer à la volée dans le modèle mongoose. (cc @m1ch3lcl pour confirmation)

2018-03-13 22:42 UTC, nymous commented on backend/src/api/resources/documents/documents.controller.js
> +        console.log(`successfully deleted ${doc.uri}`);
Pourquoi garder le `console.log` ?

2018-03-13 22:42 UTC, nymous commented on backend/src/api/resources/documents/documents.controller.js
>        return res.status(500)
Mettre ça dans un `finally` ?

2018-03-13 22:51 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +    // eslint-disable-next-line
eslint refuse que les noms des clefs commencent par underscore, sauf que c'est l'id mongo... et si tu utilises la notation crochet, il te demande d'utiliser la notation avec point

2018-03-14 06:10 UTC, Ekarz commented on backend/src/api/resources/documents/document.model.js
> +  fileName: {
original c'est le nom multer

2018-03-14 14:07 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +    doc.uri = url.resolve('/api/download/', doc._id.toString());
je plussoie :slightly_smiling_face:

2018-03-14 14:08 UTC, clementm requested changes

2018-03-14 14:08 UTC, m1ch3lcl commented on backend/src/api/resources/documents/documents.controller.js
> +        fs.unlinkSync(doc.uri);
plutôt unlink que unlinkSync

2018-03-14 14:29 UTC, clementm approved these changes

2018-03-14 14:29 UTC, nymous approved these changes

2018-03-14 14:29 UTC, merged